language:
  - cpp
compiler:
  - g++

before_install:
  # -y is for confirming Yes to add the ppa
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update

install:
  # For using c++11
  - sudo apt-get install -y g++-4.9
  # -y is for forcing Yes
  - sudo apt-get install -y build-essential

script:
  - g++ -v && cmake --version
  - make
